# Generated by Django 6.0.6 on 2026-06-27 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_alter_perfil_imagem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perfil',
            old_name='imagem',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='perfil',
            old_name='usuario',
            new_name='user',
        ),
    ]
