# Generated by Django 6.0.6 on 2026-06-07 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_alter_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.TextField(error_messages={'unique': 'Já existe um registro com este valor. Duplicatas não são permitidas!'}, max_length=255, unique=True),
        ),
    ]
