# Generated by Django 6.0.6 on 2026-06-08 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pacientes',
            name='queixa',
            field=models.CharField(choices=[('Transtorno do Déficit de Atenção com Hiperatividade', 'TDAH'), ('Depressão', 'D'), ('Ansiedade', 'A'), ('Transtorno de Ansiedade Generalizada', 'TAG')], max_length=255),
        ),
    ]
