# Generated by Django 6.0.6 on 2026-06-08 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0002_alter_pacientes_queixa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pacientes',
            name='queixa',
            field=models.CharField(choices=[('TDAH', 'Transtorno do Déficit de Atenção com Hiperatividade'), ('D', 'Depressão'), ('A', 'Ansiedade'), ('TAG', 'Transtorno de Ansiedade Generalizada')], max_length=255),
        ),
    ]
