# Generated by Django 6.0.7 on 2026-07-11 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='dcMdtvLvXM19jl2Meb0nEFiVHHTOuyaC', editable=False, max_length=32, unique=True),
        ),
    ]
