# Generated by Django 6.0.7 on 2026-07-11 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0002_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='fchJxXfauVw84nEnDJMhBxNVmnY2cfIj', editable=False, max_length=32, unique=True),
        ),
    ]
