# Generated by Django 6.0.7 on 2026-07-11 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0003_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='xTQKiP7TgaSNhg4D1LCASHLqhXASoWfb', editable=False, max_length=32, unique=True),
        ),
    ]
