# Generated by Django 6.0.6 on 2026-07-01 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0006_alter_emprestimo_data_devolucao_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emprestimo',
            name='nome_emprestado_fora',
        ),
        migrations.RemoveField(
            model_name='emprestimo',
            name='tempo_duracao',
        ),
    ]
