# Generated by Django 6.0.6 on 2026-07-04 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0007_remove_emprestimo_nome_emprestado_fora_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emprestimo',
            name='avaliacao',
            field=models.CharField(choices=[('P', 'Péssimo'), ('R', 'Ruim'), ('B', 'Bom'), ('O', 'Ótimo')], default=1, max_length=1),
            preserve_default=False,
        ),
    ]
