# Generated by Django 6.0.6 on 2026-07-04 11:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0009_alter_emprestimo_avaliacao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprestimo',
            name='data_emprestimo',
            field=models.DateTimeField(default=datetime.datetime(2026, 7, 4, 8, 39, 22, 817878)),
        ),
    ]
