# Generated by Django 6.0.6 on 2026-07-06 14:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0011_livros_img_alter_emprestimo_data_emprestimo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprestimo',
            name='data_emprestimo',
            field=models.DateTimeField(default=datetime.datetime(2026, 7, 6, 11, 55, 21, 321914)),
        ),
    ]
