# Generated by Django 6.0.6 on 2026-07-12 15:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0013_alter_emprestimo_data_emprestimo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprestimo',
            name='data_emprestimo',
            field=models.DateTimeField(default=datetime.datetime(2026, 7, 12, 12, 16, 27, 879775)),
        ),
        migrations.AlterField(
            model_name='livros',
            name='img',
            field=models.ImageField(blank=True, default='capa_livro/capa_padrao.jpg', null=True, upload_to='capa_livro'),
        ),
    ]
