# Generated by Django 6.0.7 on 2026-07-11 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'verbose_name': 'Notificaçõe'},
        ),
    ]
